.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH blaze 1  "blaze " 
.SH NAME
blaze \- A Minimal And Fast NodeJS Package Manager Written In Rust
.SH SYNOPSIS
\fBblaze\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A Minimal And Fast NodeJS Package Manager Written In Rust
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
blaze\-install(1)
install a new NodeJS package
.TP
blaze\-init(1)
initialize a new NodeJS project
.TP
blaze\-version(1)
Print the version
.TP
blaze\-help(1)
Print this message or the help of the given subcommand(s)
